<?php

namespace Database\Seeders;

use App\Models\Matrix;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class MatrixSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $matriks = [
            [
                'alternatif_id' => 1,
                'kriteria_id' => 1,
                'value' => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 1,
                'kriteria_id' => 2,
                'value' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 1,
                'kriteria_id' => 3,
                'value' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 1,
                'kriteria_id' => 4,
                'value' => 53780000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 1,
                'kriteria_id' => 5,
                'value' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 2,
                'kriteria_id' => 1,
                'value' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 2,
                'kriteria_id' => 2,
                'value' => 7.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 2,
                'kriteria_id' => 3,
                'value' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 2,
                'kriteria_id' => 4,
                'value' => 18900000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 2,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 3,
                'kriteria_id' => 1,
                'value' => 3.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 3,
                'kriteria_id' => 2,
                'value' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 3,
                'kriteria_id' => 3,
                'value' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 3,
                'kriteria_id' => 4,
                'value' => 1290000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 3,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 4,
                'kriteria_id' => 1,
                'value' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 4,
                'kriteria_id' => 2,
                'value' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 4,
                'kriteria_id' => 3,
                'value' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 4,
                'kriteria_id' => 4,
                'value' => 1340000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 4,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 5,
                'kriteria_id' => 1,
                'value' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 5,
                'kriteria_id' => 2,
                'value' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 5,
                'kriteria_id' => 3,
                'value' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 5,
                'kriteria_id' => 4,
                'value' => 160000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 5,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 6,
                'kriteria_id' => 1,
                'value' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 6,
                'kriteria_id' => 2,
                'value' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 6,
                'kriteria_id' => 3,
                'value' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 6,
                'kriteria_id' => 4,
                'value' => 198000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 6,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 7,
                'kriteria_id' => 1,
                'value' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 7,
                'kriteria_id' => 2,
                'value' => 130,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 7,
                'kriteria_id' => 3,
                'value' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 7,
                'kriteria_id' => 4,
                'value' => 108900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 7,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 8,
                'kriteria_id' => 1,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 8,
                'kriteria_id' => 2,
                'value' => 68,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 8,
                'kriteria_id' => 3,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 8,
                'kriteria_id' => 4,
                'value' => 276500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 8,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 9,
                'kriteria_id' => 1,
                'value' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 9,
                'kriteria_id' => 2,
                'value' => 2.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 9,
                'kriteria_id' => 3,
                'value' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 9,
                'kriteria_id' => 4,
                'value' => 200495,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 9,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 10,
                'kriteria_id' => 1,
                'value' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 10,
                'kriteria_id' => 2,
                'value' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 10,
                'kriteria_id' => 3,
                'value' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 10,
                'kriteria_id' => 4,
                'value' => 108090,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif_id' => 10,
                'kriteria_id' => 5,
                'value' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        Matrix::insert($matriks);
    }
}
